CREATE TABLE IF NOT EXISTS Users (
  UserID INT PRIMARY KEY AUTO_INCREMENT,
  Username VARCHAR(255),
  Email VARCHAR(255),
  Password VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Threads (
  ThreadID INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(255),
  PostDate DATETIME,
  UserID INT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS Comments (
  CommentID INT PRIMARY KEY AUTO_INCREMENT,
  Body VARCHAR(255),
  PostDate DATETIME,
  UserID INT,
  ThreadID INT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (ThreadID) REFERENCES Threads(ThreadID)
);

CREATE TABLE IF NOT EXISTS Likes (
  LikeID INT PRIMARY KEY AUTO_INCREMENT,
  UserID INT,
  CommentID INT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (CommentID) REFERENCES Comments(CommentID)
);
